- name: Ansible data types
  hosts: local
  connection: local
  vars_prompt:
    - name: number
      prompt: Please enter the number
      private: false
  tasks:
  - name: checking number greater than 20
    ansible.builtin.debug:
      msg: "given number is greater than 20"
    when: number | int > 20

  - name: checking number greater than 20
    ansible.builtin.debug:
      msg: "given number {{number}} less than 20"
    when: number | int <= 20

