- name: variables
  hosts: web
  vars_files: 
  - vars_file.yaml
  vars:            # play level variables
    name1: "Srivalli"
    course: "Devops"
  tasks:
  - name: Printing play level variables
    ansible.builtin.debug:
      msg: "My name is {{name1}} and my course is {{course}} duration is {{hrs}} and mode is {{mode}}"
 
