- name: variables from prompt
  hosts: web
  vars_prompt:
    - name: sname
      prompt: please enter name
      private: false # not confidential
    - name: course
      prompt: please enter course
      private: false # not confidential
  tasks:
  - name: Printing prompt variables
    ansible.builtin.debug:
      msg: "My name is {{sname}} and my course is {{course}}"


